## Docker image for Python

## Components installed
## - Python 3.12

FROM ubuntu:20.04
 
LABEL maintainer=whereq@gmail.com

#ENV http_proxy http://proxy:port
#ENV https_proxy http://proxy:port

## Install Python 3.12
RUN apt-get update && \
	apt install software-properties-common -y && \
	add-apt-repository ppa:deadsnakes/ppa  && \
	apt install python3.12 -y && \
	apt-get clean


## install pip/create link for python 3.12
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12 && \
    ln -s /usr/bin/python3.12 /usr/bin/python

RUN mkdir -p /app

## Remove proxy
# ENV http_proxy="" https_proxy=""